[application]
name = "regs-tt"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
base_path = "/regs-tt/"
title = "Regs TT"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
