[application]

# App (Project) Name
name = "regs-tt"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[web.app]

base_path = "/regs-tt/"

# HTML title tag content
title = "regs-tt"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]
